In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
cancer = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cancer.csv')
cancer.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

**2. Data Preprocessing**

In [4]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [6]:
cancer.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [5]:
cancer.duplicated().sum()

0

In [6]:
cancer.drop('Unnamed: 32',axis=1,inplace=True)

In [9]:
cancer.corr(numeric_only=True)

id  radius_mean  texture_mean  perimeter_mean  \
id                       1.000000     0.074626      0.099770        0.073159   
radius_mean              0.074626     1.000000      0.323782        0.997855   
texture_mean             0.099770     0.323782      1.000000        0.329533   
perimeter_mean           0.073159     0.997855      0.329533        1.000000   
area_mean                0.096893     0.987357      0.321086        0.986507   
smoothness_mean         -0.012968     0.170581     -0.023389        0.207278   
compactness_mean         0.000096     0.506124      0.236702        0.556936   
concavity_mean           0.050080     0.676764      0.302418        0.716136   
concave points_mean      0.044158     0.822529      0.293464        0.850977   
symmetry_mean           -0.022114     0.147741      0.071401        0.183027   
fractal_dimension_mean  -0.052511    -0.311631     -0.076437       -0.261477   
radius_se                0.143048     0.679090      0.275869        0.691765   
texture_se              -0.007526    -0.097317      0.386358       -0.086761   
perimeter_se             0.137331     0.674172      0.281673        0.693135   
area_se                  0.177742     0.735864      0.259845        0.744983   
smoothness_se            0.096781    -0.222600      0.006614       -0.202694   
compactness_se           0.033961     0.206000      0.191975        0.250744   
concavity_se             0.055239     0.194204      0.143293        0.228082   
concave points_se        0.078768     0.376169      0.163851        0.407217   
symmetry_se             -0.017306    -0.104321      0.009127       -0.081629   
fractal_dimension_se     0.025725    -0.042641      0.054458       -0.005523   
radius_worst             0.082405     0.969539      0.352573        0.969476   
texture_worst            0.064720     0.297008      0.912045        0.303038   
perimeter_worst          0.079986     0.965137      0.358040        0.970387   
area_worst               0.107187     0.941082      0.343546        0.941550   
smoothness_worst         0.010338     0.119616      0.077503        0.150549   
compactness_worst       -0.002968     0.413463      0.277830        0.455774   
concavity_worst          0.023203     0.526911      0.301025        0.563879   
concave points_worst     0.035174     0.744214      0.295316        0.771241   
symmetry_worst          -0.044224     0.163953      0.105008        0.189115   
fractal_dimension_worst -0.029866     0.007066      0.119205        0.051019   

                         area_mean  smoothness_mean  compactness_mean  \
id                        0.096893        -0.012968          0.000096   
radius_mean               0.987357         0.170581          0.506124   
texture_mean              0.321086        -0.023389          0.236702   
perimeter_mean            0.986507         0.207278          0.556936   
area_mean                 1.000000         0.177028          0.498502   
smoothness_mean           0.177028         1.000000          0.659123   
compactness_mean          0.498502         0.659123          1.000000   
concavity_mean            0.685983         0.521984          0.883121   
concave points_mean       0.823269         0.553695          0.831135   
symmetry_mean             0.151293         0.557775          0.602641   
fractal_dimension_mean   -0.283110         0.584792          0.565369   
radius_se                 0.732562         0.301467          0.497473   
texture_se               -0.066280         0.068406          0.046205   
perimeter_se              0.726628         0.296092          0.548905   
area_se                   0.800086         0.246552          0.455653   
smoothness_se            -0.166777         0.332375          0.135299   
compactness_se            0.212583         0.318943          0.738722   
concavity_se              0.207660         0.248396          0.570517   
concave points_se         0.372320         0.380676          0.642262   
symmetry_s


Encoding the Target Variable

In [7]:
cancer['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [8]:
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#cancer['diagnosis'] = le.fit_transform(cancer['diagnosis'])
cancer['diagnosis'] = cancer['diagnosis'].map({'M':1,'B':0})


**Splitting Data into Training and Testing Sets**

In [9]:
from sklearn.model_selection import train_test_split
X = cancer.drop('diagnosis',axis=1)
y = cancer['diagnosis']
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
X_train.shape

(455, 31)

In [11]:
X_test.shape

(114, 31)

**Feature Scaling**

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [13]:
sc.fit(X_train)

StandardScaler()

In [14]:
sc.fit(X_test)

StandardScaler()

In [16]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train

array([[-0.24823501, -1.477576  , -0.53865876, ...,  0.87224493,
         2.38202515,  1.76038862],
       [-0.24807583,  1.99169056,  1.55507404, ...,  2.58548659,
         2.15166754,  2.33760025],
       [-0.24823811, -1.43615536, -1.32494153, ..., -0.97220162,
         0.70573054,  0.03404926],
       ...,
       [-0.15747984,  0.03571572, -0.65422193, ..., -1.23282832,
        -0.75438232, -1.22098886],
       [-0.24768247, -0.05345372, -0.01975745, ...,  0.98665916,
         0.52321643,  1.12492628],
       [-0.24819563, -0.57121177,  0.18417757, ..., -0.62390687,
        -0.33619465, -0.81958849]])

**Training Model**

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [19]:
lr.fit(X_train,y_train)

LogisticRegression()

In [22]:
y_pred = lr.predict(X_test)
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1])

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
accuracy_score(y_test,y_pred)

0.9824561403508771

In [42]:
input_text = ([-2.47601291e-01, -2.20286873e-01,  1.84177566e-01, -1.51853247e-01,
       -2.95164783e-01,  8.20830904e-01,  7.33995765e-01,  6.94985735e-01,
        7.28351625e-01,  1.11305010e+00,  1.60054313e+00, -1.07690576e-01,
       -5.84945547e-01,  1.08068683e-01, -2.04823290e-01, -6.63103559e-01,
       -1.48809120e-01,  3.13948420e-01,  3.43347081e-01, -3.90187398e-01,
        1.57293954e-01,  9.68628060e-04,  5.31689849e-01,  1.56802993e-01,
       -8.77678144e-02,  1.00962266e+00,  7.53986995e-01,  1.20845507e+00,
        1.31950056e+00,  1.24264097e+00,  1.41088434e+00])
np_df = np.asarray(input_text)
prediciont = lr.predict(np_df.reshape(1,-1))

if(prediciont[0]==1):
  print('Cancrous')
else:
  print('Not Cancrous')

Cancrous


In [40]:
X_train[30]

array([-2.47601291e-01, -2.20286873e-01,  1.84177566e-01, -1.51853247e-01,
       -2.95164783e-01,  8.20830904e-01,  7.33995765e-01,  6.94985735e-01,
        7.28351625e-01,  1.11305010e+00,  1.60054313e+00, -1.07690576e-01,
       -5.84945547e-01,  1.08068683e-01, -2.04823290e-01, -6.63103559e-01,
       -1.48809120e-01,  3.13948420e-01,  3.43347081e-01, -3.90187398e-01,
        1.57293954e-01,  9.68628060e-04,  5.31689849e-01,  1.56802993e-01,
       -8.77678144e-02,  1.00962266e+00,  7.53986995e-01,  1.20845507e+00,
        1.31950056e+00,  1.24264097e+00,  1.41088434e+00])

In [44]:
import pickle
pickle.dump(lr,open('model.pkl','wb'))